name: YSpigotSkyfall
version: 1.0.1
author: YodaSoda_HD
main: org.YodaSoda_HD.YSpigotSkyfall.Main
description: The second version of YodaSoda's own Gamemode.

commands:
  listPlayers: 
    description: list all Players
  skyfalladmin: