version: 3.1
author: Vayion
name: Skyfall
main: org.vayion.skyfall.Main

commands:
  start:
  setFlag:
  joinTeam:
  setspawn:
  saveInventory:
  toggleedit:
  setLobbySpawn:
  setSpecSpawn:
  selectClass: